version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cortex
      POSTGRES_USER: cortex
      POSTGRES_PASSWORD: cortex123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cortex"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  nocobase:
    image: nocobase/nocobase:latest
    environment:
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: cortex
      DB_USER: cortex
      DB_PASSWORD: cortex123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_KEY: cortex-secret-key-change-in-production
    ports:
      - "13000:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
      - ./packages:/app/packages
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/app:getInfo"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  postgres_data:
  redis_data:
